name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-release-draft:
    name: Update draft release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # Required to create and update the draft release.
      pull-requests: read # Required to compile merged pull request details.
    steps:
      - name: Update the draft release
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
